name: Release Charts

on:
  push:
    branches:
      - main
    paths:
      - 'helm/**'
env:
  HELM_EXPERIMENTAL_OCI: 1 #enable OCI support
  HELM_VERSION_TO_INSTALL: 3.10.1 # version of HELM to install
  GCR_IMAGE: ghcr.io/${{ github.repository_owner }}/portail-formation-demo
  CHART_NAME: portail-formation-demo
  IMAGE_TAG: 0.1.0

jobs:
  build-chart:
    name: publish gcr
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: checkout repo
      
      - name: install helm
        uses: Azure/setup-helm@v1
        with:
          # Version of helm
          version: ${{ env.HELM_VERSION_TO_INSTALL }} # default is latest
      
      - name: helm lint
        run: |
          helm lint ${{ github.workspace }}/helm/portail-formation-backend/

      - name: login to gcr using helm
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | helm registry login ghcr.io --username ${{ github.repository_owner }} --password-stdin

      - name: add deps repo
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami

      - name: save helm chart to local registry
        run: |
          helm package --dependency-update ${{ github.workspace }}/helm/portail-formation-backend/ --version $IMAGE_TAG

      - name: publish chart to acr
        run: |
          helm push $CHART_NAME-$IMAGE_TAG.tgz oci://ghcr.io/nerevahr